apiVersion: apps/v1
kind: Deployment
metadata:
  name: axum-api
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: api-container
        image: ghcr.io/rhrlima/axum-api:v2024.03.07-22.10.54
        env:
        - name: ENVIRONMENT
          value: stage
