apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ricardo-test

resources:
- ../../base/axum-api

patches:
- path: deployment.yaml

images:
- name: ghcr.io/rhrlima/axum-api
  newTag: 2024.01.12-19.59.48
