name: Deploy

on: [repository_dispatch]

jobs:
  deploy:
    name: Update Image Tag
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: rhrlima/ci-actions/actions/deploy-receive@main
        with:
          IMAGE_TAG: ${{ github.event.client_payload.IMAGE_TAG }}
          IMAGE_NAME: ${{ github.event.client_payload.IMAGE_NAME }}
          MANIFEST_PATH: ${{ github.event.client_payload.MANIFEST_PATH }}
          PR_TITLE: ${{ github.event.client_payload.EVENT_TYPE }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
