apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: api-container
        image: ghcr.io/rhrlima/go-api:v0.2.1
        env:
        - name: ENVIRONMENT
          value: dev
