apiVersion: apps/v1
kind: Deployment
metadata:
  name: another-app
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: api-container
        image: ghcr.io/datarisk-io/datapi-test-deploy:v2024.03.11-15.06.51
        env:
        - name: ENVIRONMENT
          value: stage
